version:  '2'

services:
   op5:
     image: op5com/monitor-docker
     restart: always
     env_file:
       - variables.env
     privileged: true
     ports:
       - "162:162/udp"
       - "162:162/tcp"
       - "2222:2222"
       - "80:80"
       - "433:443"
       - "5666:5666"
       - "15551:15551" 
