version:  '2'

services:
   op5:
     image: ${IMAGE}
     restart: always
     env_file:
       - variables.env
     privileged: true
     ports:
       - "162:162/udp"
       - "162:162/tcp"
       - "2222:22"
       - "8080:80"
       - "4433:443"
       - "5666:5666"
       - "15551:15551" 
